index:
    path: /
    controller: App\Controller\LouvreController::index

recapitulatif:
    path: /recap
    controller: App\Controller\LouvreController::recapitulatif

paiement:
    path: /paiement
    controller: App\Controller\LouvreController::paiement