#index:
#    path: /
#    controller: App\Controller\DefaultController::index
recapitulatif:
    path: /recap
    controller: App\Controller\LouvreController::recapitulatif

paiement:
    path: /paiement
    controller: App\Controller\LouvreController::paiement


test:
    path: /test
    controller: App\Controller\LouvreController::test